FROM node:16.20.0 as build
WORKDIR /app
COPY package*.json ./
RUN node --version && npm --version
RUN npm install
COPY . .
RUN npx react-scripts build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]