services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3001:3001"
    volumes:
      - ./server/data:/app/data
    environment:
      - mongodb://db:27017/moviejab-server
      - PORT=3001
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "80:80"
  db:
    image: mongo
    volumes:
      - ./data:/data/db